In [18]:
import gensim.downloader as api

model = api.load("glove-twitter-200")  # load glove vectors

In [21]:
model.most_similar("king")

[('prince', 0.7170549035072327),
 ('queen', 0.6889298558235168),
 ('aka', 0.6471514105796814),
 ('kings', 0.6193956136703491),
 ('burger', 0.6085751056671143),
 ('the', 0.6077988743782043),
 ("'s", 0.597236156463623),
 ('legend', 0.5925674438476562),
 ('john', 0.5862494707107544),
 ('jack', 0.5856382846832275)]

In [19]:
model.most_similar("cat")  # show words that similar to word 'cat'

[('dog', 0.8324302434921265),
 ('cats', 0.7685185074806213),
 ('kitty', 0.750445544719696),
 ('kitten', 0.7489697933197021),
 ('pet', 0.7319862842559814),
 ('puppy', 0.7023192048072815),
 ('dogs', 0.7016381621360779),
 ('animal', 0.6421107649803162),
 ('bear', 0.6309185028076172),
 ('meow', 0.6304775476455688)]

In [4]:
v_queen = model['queen']
v_queen

array([-0.66519  ,  0.13326  , -0.17055  ,  0.21867  ,  0.15768  ,
       -0.48743  ,  0.53099  ,  0.25983  ,  0.25182  , -0.15435  ,
       -0.6427   ,  0.31891  , -0.59868  ,  0.25494  ,  0.070109 ,
        1.0979   ,  0.38859  ,  0.21592  , -0.20378  ,  0.57565  ,
        0.21505  , -0.185    , -0.055782 ,  0.29271  ,  0.52882  ,
       -0.045739 ,  0.047956 , -0.39593  ,  0.46911  ,  0.35171  ,
        0.82535  , -0.29078  ,  0.27657  , -0.36322  , -0.13025  ,
       -0.70333  ,  0.03359  ,  0.047684 , -0.075103 , -0.13727  ,
       -0.1266   , -0.59034  ,  0.61091  , -0.56001  ,  0.060225 ,
        0.092128 , -0.15561  ,  0.29311  , -0.020907 , -0.24135  ,
        0.26977  , -0.67593  ,  0.36445  ,  0.13478  ,  0.36163  ,
        0.47267  , -0.29799  ,  0.33279  , -0.54997  ,  0.32127  ,
       -0.27397  ,  0.20474  , -0.019486 , -0.27385  , -0.28868  ,
        0.053527 , -0.27204  ,  0.40046  ,  0.3723   , -0.5716   ,
       -0.14386  , -0.22176  , -0.3895   ,  0.19305  ,  0.0930

In [5]:
v_king = model['king']
v_king

array([-3.1949e-01,  1.0382e-01,  2.4294e-01, -3.4845e-01, -2.3829e-01,
       -3.7200e-01,  3.7950e-01, -3.0334e-01, -2.1441e-01, -4.9230e-01,
        9.8965e-02, -1.3791e-01, -8.0118e-01,  5.0410e-02,  3.9894e-02,
        8.7262e-01,  4.4222e-01, -3.2196e-01,  6.5187e-01,  1.1450e-01,
       -3.0635e-01,  1.3293e-01, -6.8867e-03, -1.5688e-01,  1.9338e-01,
       -2.8577e-01,  2.6790e-01,  2.4383e-01,  1.5909e-02,  7.6273e-02,
        5.8036e-01, -7.1514e-02,  2.0632e-01, -3.0900e-01,  3.0187e-01,
        1.2900e-01, -1.4297e-01, -7.9204e-02,  2.5754e-01, -5.9380e-01,
       -1.2120e-03,  3.0647e-01,  8.3300e-01, -5.4968e-02,  1.3717e-01,
       -1.1724e-01,  2.8900e-01,  2.3425e-01,  3.5452e-01,  1.3312e-01,
       -1.4014e-01, -1.0090e+00,  2.1142e-01,  5.3368e-01,  1.3168e-01,
       -1.3271e-01,  2.5046e-01,  2.8531e-02, -6.4371e-01,  5.6957e-02,
       -4.9754e-01, -7.1232e-03, -4.0831e-01, -3.9913e-01, -5.9560e-01,
       -5.8436e-01,  8.5161e-02,  3.7481e-01,  8.2033e-02, -3.23

In [6]:
v_man = model['man']
v_man

array([-1.8589e-01,  1.1154e-01, -5.0682e-02, -6.3826e-02, -5.8336e-01,
        3.3422e-01, -1.7507e-02,  1.3963e-01,  2.7304e-01, -2.6348e-01,
       -4.9026e-02,  4.2655e-01, -1.1880e-01,  1.9911e-01,  1.0068e-01,
        1.8300e-01,  8.7745e-01, -9.5188e-02,  1.9613e-01, -4.3530e-01,
       -4.7063e-01,  8.6615e-01,  1.7380e-01,  3.8348e-01, -5.4303e-01,
        1.1275e-01, -1.1005e-01,  5.9487e-04, -3.8883e-01, -6.3458e-01,
       -3.2093e-01,  2.5385e-01,  1.2499e-01, -4.1472e-01,  1.8170e-01,
        6.4896e-01, -4.4274e-01, -2.1635e-01,  6.9014e-03, -5.8780e-01,
       -5.6062e-01,  3.7875e-01,  2.2241e-02,  1.3305e-01, -5.7258e-01,
        1.4772e-01,  5.1383e-01,  8.0338e-01,  1.0101e-01,  2.2314e-01,
       -8.8118e-01,  2.6991e-01,  2.1527e-01, -1.7186e-01, -3.5966e-01,
       -3.6161e-01, -5.1107e-01,  2.3336e-01, -2.7255e-01, -1.1736e-01,
       -1.0297e-01, -1.3622e-01,  2.8126e-02, -8.0522e-02, -2.6604e-01,
       -1.7727e-01,  5.7371e-01,  4.0621e-01, -7.3750e-01,  3.00

In [7]:
v_woman = model['woman']
v_woman

array([-5.8108e-01,  6.9252e-02, -2.1020e-01,  4.7329e-01, -5.7045e-01,
       -1.2728e-01,  5.8206e-01,  3.5802e-01,  3.2133e-01,  3.2887e-01,
       -5.4328e-01,  5.3099e-01, -5.6408e-01,  5.4484e-02,  5.9776e-02,
        1.2688e-01,  5.7681e-01,  1.3027e-01,  6.9471e-01, -4.9994e-01,
        4.2699e-01,  1.4618e-01, -4.9162e-01, -1.0230e-01,  7.1386e-03,
        1.3478e+00, -3.2241e-01, -2.0952e-01,  3.1126e-01,  3.4731e-02,
        6.4602e-02, -7.8394e-02, -1.6410e-02, -1.9923e-01, -1.0598e-01,
        1.9101e-01, -3.2951e-01,  1.6410e-01,  2.1120e-01,  3.7300e-02,
        4.8447e-01, -4.2968e-01, -7.5234e-03, -1.7277e-01,  1.3229e-01,
        1.8498e-01,  7.7002e-01,  1.0267e+00, -6.7403e-01, -1.5247e-02,
       -5.7557e-01,  4.1458e-01, -3.1765e-01, -6.8267e-01,  3.9020e-01,
        3.5896e-01, -4.5137e-02,  3.3141e-01, -2.6424e-01,  1.5473e-01,
       -2.7438e-01, -1.8031e-01,  2.4498e-01, -7.7025e-02,  1.6052e-01,
        2.4104e-01,  2.4168e-01,  4.0327e-01, -1.2358e-01,  1.84

In [8]:
v_king - v_man + v_woman

array([-7.14680016e-01,  6.15320057e-02,  8.34219903e-02,  1.88665986e-01,
       -2.25380003e-01, -8.33500028e-01,  9.79066968e-01, -8.49499702e-02,
       -1.66119993e-01,  1.00050002e-01, -3.95289004e-01, -3.34699750e-02,
       -1.24645996e+00, -9.42160040e-02, -1.01000071e-03,  8.16500008e-01,
        1.41580015e-01, -9.65020061e-02,  1.15044999e+00,  4.98599708e-02,
        5.91269970e-01, -5.87040067e-01, -6.72306716e-01, -6.42660022e-01,
        7.43548632e-01,  9.49280024e-01,  5.55399954e-02,  3.37151289e-02,
        7.15999007e-01,  7.45584011e-01,  9.65892017e-01, -4.03758019e-01,
        6.49200007e-02, -9.35099870e-02,  1.41899809e-02, -3.28949988e-01,
       -2.97400057e-02,  3.01245987e-01,  4.61838573e-01,  3.13000195e-02,
        1.04387808e+00, -5.01959980e-01,  8.03235590e-01, -3.60787988e-01,
        8.42040002e-01, -7.99799860e-02,  5.45189977e-01,  4.57570016e-01,
       -4.20520008e-01, -1.05267003e-01,  1.65470004e-01, -8.64329934e-01,
       -3.21500003e-01,  

In [9]:
v_queen

array([-0.66519  ,  0.13326  , -0.17055  ,  0.21867  ,  0.15768  ,
       -0.48743  ,  0.53099  ,  0.25983  ,  0.25182  , -0.15435  ,
       -0.6427   ,  0.31891  , -0.59868  ,  0.25494  ,  0.070109 ,
        1.0979   ,  0.38859  ,  0.21592  , -0.20378  ,  0.57565  ,
        0.21505  , -0.185    , -0.055782 ,  0.29271  ,  0.52882  ,
       -0.045739 ,  0.047956 , -0.39593  ,  0.46911  ,  0.35171  ,
        0.82535  , -0.29078  ,  0.27657  , -0.36322  , -0.13025  ,
       -0.70333  ,  0.03359  ,  0.047684 , -0.075103 , -0.13727  ,
       -0.1266   , -0.59034  ,  0.61091  , -0.56001  ,  0.060225 ,
        0.092128 , -0.15561  ,  0.29311  , -0.020907 , -0.24135  ,
        0.26977  , -0.67593  ,  0.36445  ,  0.13478  ,  0.36163  ,
        0.47267  , -0.29799  ,  0.33279  , -0.54997  ,  0.32127  ,
       -0.27397  ,  0.20474  , -0.019486 , -0.27385  , -0.28868  ,
        0.053527 , -0.27204  ,  0.40046  ,  0.3723   , -0.5716   ,
       -0.14386  , -0.22176  , -0.3895   ,  0.19305  ,  0.0930

In [10]:
import numpy as np
from numpy.linalg import norm

In [11]:
def cosine_distance(A, B):
    return 1.0-np.dot(A,B)/(norm(A)*norm(B))

In [12]:
cosine_distance(v_king, v_queen)

0.31107020378112793

In [13]:
model.most_similar("queen")  # show words that similar to word

[('princess', 0.737736701965332),
 ('king', 0.6889297962188721),
 ('queens', 0.6338734030723572),
 ('diva', 0.6218307018280029),
 ('lady', 0.6180005073547363),
 ('gaga', 0.5943964123725891),
 ('she', 0.5913893580436707),
 ('prince', 0.590600311756134),
 ('girl', 0.5876660346984863),
 ('beyonce', 0.5821259617805481)]

In [14]:
cosine_distance(v_king-v_man+v_woman, v_queen)

0.3439820408821106

In [15]:
model.most_similar(positive=['king', 'woman'], negative=['man'])

[('queen', 0.6820898652076721),
 ('prince', 0.5875527262687683),
 ('princess', 0.5620488524436951),
 ('royal', 0.5522865056991577),
 ('mother', 0.5362966656684875),
 ('elizabeth', 0.5142496228218079),
 ('lady', 0.5010437965393066),
 ('lion', 0.4998807907104492),
 ('women', 0.4985955059528351),
 ('’s', 0.4935073256492615)]

In [23]:
model.most_similar('king')

[('prince', 0.7170549035072327),
 ('queen', 0.6889298558235168),
 ('aka', 0.6471514105796814),
 ('kings', 0.6193956136703491),
 ('burger', 0.6085751056671143),
 ('the', 0.6077988743782043),
 ("'s", 0.597236156463623),
 ('legend', 0.5925674438476562),
 ('john', 0.5862494707107544),
 ('jack', 0.5856382846832275)]

In [16]:
model.most_similar(positive=['king'], negative=['man'])

[('burguer', 0.40164196491241455),
 ('kester', 0.36745598912239075),
 ('سنتان', 0.35920560359954834),
 ('sejong', 0.3575325906276703),
 ('soopers', 0.3511844575405121),
 ('hrh', 0.348835289478302),
 ('gabin', 0.34134572744369507),
 ('b.b', 0.3367059826850891),
 ('zamir', 0.33550915122032166),
 ('balthazar', 0.3281760513782501)]

In [17]:
model.most_similar(positive=['uk', 'paris'], negative=['london'])

[('france', 0.6881362795829773),
 ('europe', 0.5892561674118042),
 ('au', 0.5266880393028259),
 ('tour', 0.5142650008201599),
 ('avril', 0.5129667520523071),
 ('canada', 0.5057218670845032),
 ('est', 0.5039017200469971),
 ('ce', 0.5004457235336304),
 ('à', 0.5003809928894043),
 ('pour', 0.49527785181999207)]